'use client';

import { useContext, useState } from 'react';
import styles from '../page.module.sass';
import SessionContext from '../contexts/sessionContext';
import Navbar from '../components/Navbar';
import Categories from '../components/Categories';

export const metadata = {
	title: 'Gate7 App',
	description: 'Generated by gothmate',
};

export default function UserHomeLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = useContext(SessionContext);

	const [data, setData] = useState(false);

	const menuData = (newData: boolean) => {
		setData(newData);
	};

	return (
		<SessionContext.Provider value={session}>
			<div id={styles.basePage}>
				<Navbar
					user={session.user}
					avatar={session.avatar}
					nome={session.name}
					menuInfo={menuData}
				/>
				<div id={styles.content}>
					<Categories menu={data} />
					<main className={styles.mainPage}>{children}</main>
				</div>
			</div>
		</SessionContext.Provider>
	);
}
