'use client';

import { useContext } from 'react';
import styles from '../page.module.sass';
import SessionContext from '../contexts/sessionContext';
import Navbar from '../components/Navbar';
import Categories from '../components/Categories';

export const metadata = {
	title: 'Gate7 App',
	description: 'Generated by gothmate',
};

export default function UserHomeLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = useContext(SessionContext);
	return (
		<SessionContext.Provider value={session}>
			<div id={styles.basePage}>
				<Navbar user={session.user} />
				<div id={styles.content}>
					<Categories />
					<main className={styles.mainPage}>{children}</main>
				</div>
			</div>
		</SessionContext.Provider>
	);
}
