import './globals.sass'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gate7 App',
  description: 'Generated by gothmate'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang='pt-br'>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
